### ISSUE TITLE
How to set bot token

### ISSUE THREAD

**Issue by donkeymonkey1** [bananaprotocol/confax#16]

**Comment by donkeymonkey1** [comment]
Fixed

**Comment by bananaprotocol** [comment]
Glad you got it to work. Have fun using Confax!

**Comment by marvinpoo** [comment]
Just for everyone else who is looking for this and because no answer was set here, currently you set the bot token by renaming `.env.example` in the root directory of your bot to `.env` and add the token in the `.env` file.
