### ISSUE TITLE
No guild configuration file makes the bot crash when the first message is received in the banwords module

### ISSUE THREAD

**Issue by sietse85** [bananaprotocol/confax#42]
reproduce by having the guilds/ folder empty

@bananaprotocol 
banwords.js
`const config = Confax.getConfig(message.guild.id)`

**Comment by sietse85** [comment]
reproduce by having the guilds/ folder empty

**Comment by bananaprotocol** [comment]
I have noticed this problem too, will look into it.

**Comment by GlassToeStudio** [comment]
Fixed in: https://github.com/bananaprotocol/confax/pull/43#issue-465046630
